[package]
name = "gui"
typ = "dynlib"
src = ["src/components", "src/gfx"]
outdir = "."
gen_config = false

[compiler]
includes = ["include", "lib/cglm/include", "lib/stb", "lib/gaia/include", "lib/freetype", "lib/glad/include", "lib/glfw/include"]
flags = ["-std=c11", "-O3", "-g", "-Wall", "-Wextra", "-Wpedantic", "-Wstrict-aliasing", "-Wno-newline-eof", "-Wno-deprecated-declarations", "-Wno-unused-parameter", "-DDLL_BUILD"]

[linker]
libs = ["lib/cglm/libcglm.a", "lib/gaia/libgaia.lib", "lib/freetype/freetype.lib", "lib/glad/src/glad.o", "lib/glfw/glfw3dll.lib"]
